task:
  name: "sd cpu"
  timeout_in: 90m  
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
        
  script:
       - DEBIAN_FRONTEND=noninteractive
       - apt-get update -y
       - apt-get upgrade -y
       - apt-get install -y git
       - git config --global user.name "harik1708"
       - git config --global user.email "hariv1708@gmail.com"
       - git config --global color.ui true
       - apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git
       - apt-get install -y openjdk-11-jdk
       - apt-get install -y wget
       - apt-get install -y jq
       - git clone https://github.com/akhilnarang/scripts bscripts && cd bscripts && bash setup/android_build_env.sh && cd ..
       - git lfs install
       - git clone https://huggingface.co/phoenix-1708/SD_CPU
       - cd SD_CPU
       - unzip sd.webui.cpu.zip
       - cd sd.webui.cpu
       - pip install "fastapi[all]"
       - bash run.sh


